### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'project'

### ISSUE THREAD

**Issue by januszsowa** [gongouveia/Whisper-Temple-Synthetic-ASR-Dataset-Generator#2]
Hi, really looking forward to try your project - looks very interesting and exactly something that I was lookink for but I'm getting an error when tryin to run it:

```
**(WhisperTemple) C:\Users\janus\Desktop\Dataset\Syntehtic-Speech-Dataset-Generator>python temple.py -p PROJECT -t auto**
GPU available: False

Project found. Continue and Visualize Dataset.

Generating speech with the following parameters:
Traceback (most recent call last):
  File "C:\Users\janus\Desktop\Dataset\Syntehtic-Speech-Dataset-Generator\temple.py", line 56, in <module>
    main()
  File "C:\Users\janus\Desktop\Dataset\Syntehtic-Speech-Dataset-Generator\temple.py", line 43, in main
    write_config_dictionary(vars(args), torch.cuda.is_available())
  File "C:\Users\janus\Desktop\Dataset\Syntehtic-Speech-Dataset-Generator\Utils\ConfigHandle.py", line 7, in write_config_dictionary
    configs = {'project_name': args.project ,
                               ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'project'
```

Any idea? seems that the Project was found (I've tried different names as well). Using windows 10 with miniconda3 installed

**Comment by gongouveia** [comment]
@januszsowa Hello, thank you for using my project.
I solved the issue, it was in the `temple.py` file.
There are some more small bug.
Please note that at first when downloading the model it takes time.

I would be glad if you could add more issues and contribute to the project.
I will try to update and fix problems on the daily basis :)
